### PR TITLE
Rudimentary script for after an update

### PR DESCRIPTION
**Pull request by taotien**
This is the script I use to quickly run all the steps again. Needs some polish and documentation but works for now.

### CODE REVIEW

**Comment by Trevo525** [comment]
I will try this either tonight or tomorrow. Thank you for your patience.

**Comment by Trevo525** [comment]
I should have asked earlier, so forgive me. Have you tried this on 3.1 or 3.2? 3.2 might just be beta right now. I have been too busy to keep up with all of it right now. I had a user say that 3.1 might have changed how the mounting/formatting works and my whole script might not work on it.

**Comment by taotien** [comment]
Interesting. I've been running 3.1 Stable which has been fine, although I just installed the beta for 3.2 so I'll diff the files and check it out.

**Comment by taotien** [comment]
The mounting file hasn't changed, but the formatting one has.

```
$ diff -y --suppress-common-lines /usr/lib/hwsupport/format-sdcard.sh unmodified/format-sdcard.sh

SDCARD_DEVICE="/dev/mmcblk0"                                  <
SDCARD_PARTITION="/dev/mmcblk0p1"                             <
FORCE_FORMAT=0                                                <
while [[ $# -gt 0 ]]; do                                      | if [[ -e /dev/mmcblk0 ]]
    case "$1" in                                              | then
        --force) FORCE_FORMAT=1; shift ;;                     |    systemctl stop sdcard-mount@mmcblk0p1.service
        *) echo "Unknown option $1"; exit 22;;                |    # lock file prevents the mount service from re-mounting as
    esac                                                      |    echo $$ > $MOUNT_LOCK
done                                                          |    parted --script /dev/mmcblk0 mklabel gpt mkpart primary 0%
                                                              |    sync
if [[ ! -e "$SDCARD_DEVICE" ]]; then                          |    mkfs.ext4 -m 0 -O casefold -F /dev/mmcblk0p1
    exit 19 #ENODEV                                           |    sync
                                                              >    rm $MOUNT_LOCK
                                                              >    systemctl start sdcard-mount@mmcblk0p1.service
                                                              >    exit 0
systemctl stop sdcard-mount@mmcblk0p1.service                 | exit 1
                                                              <
# lock file prevents the mount service from re-mounting as it <
on_exit() { rm -f -- "$MOUNT_LOCK"; }                         <
trap on_exit EXIT                                             <
echo $$ > "$MOUNT_LOCK"                                       <
                                                              <
# Test the sdcard                                             <
# Some fake cards advertise a larger size than their actual c <
# which can result in data loss or other unexpected behaviour <
# best to try to detect these issues as early as possible.    <
if [[ "$FORCE_FORMAT" == "0" ]]; then                         <
    echo "stage=testing"                                      <
    if ! f3probe --destructive "$SDCARD_DEVICE"; then         <
        # Fake sdcards tend to only behave correctly when for <
        # The tricks they try to pull fall apart with any oth <
        # it renders the card unusuable.                      <
        #                                                     <
        # Here we restore the card to exfat so that it can be <
        # It won't be usable with the deck, and usage of the  <
        # result in data loss. We return a special error code <
        # a specific error to the user.                       <
        echo "stage=rescuing"                                 <
        echo "Bad sdcard - rescuing"                          <
        for i in {1..3}; do # Give this a couple of tries sin <
            echo "Create partition table: $i"                 <
            dd if=/dev/zero of="$SDCARD_DEVICE" bs=512 count= <
            if ! parted --script "$SDCARD_DEVICE" mklabel msd <
                echo "Failed to create partition table: $i"   <
                continue # try again                          <
            fi                                                <
                                                              <
            echo "Create exfat filesystem: $i"                <
            sync                                              <
            if ! mkfs.exfat "$SDCARD_PARTITION"; then         <
                echo "Failed to exfat filesystem: $i"         <
                continue # try again                          <
            fi                                                <
                                                              <
            echo "Successfully restored device"               <
            break                                             <
        done                                                  <
                                                              <
        # Return a specific error code so the UI can warn the <
        exit 14 # EFAULT                                      <
    fi                                                        <
fi                                                            <
                                                              <
# Clear out the garbage bits generated by f3probe from the pa <
# Otherwise parted may think we have existing partitions in a <
dd if=/dev/zero of="$SDCARD_DEVICE" bs=512 count=1024         <
                                                              <
# Format as EXT4 with casefolding for proton compatibility    <
echo "stage=formatting"                                       <
sync                                                          <
parted --script "$SDCARD_DEVICE" mklabel gpt mkpart primary 0 <
sync                                                          <
mkfs.ext4 -m 0 -O casefold -F "$SDCARD_PARTITION"             <
sync                                                          <
                                                              <
rm "$MOUNT_LOCK"                                              <
systemctl start sdcard-mount@mmcblk0p1.service                <
                                                              <
exit 0                                                        <
```

**Comment by taotien** [comment]
I'll see if I can add the update checking logic later, for now I have a midterm! :crying_cat_face:

**Comment by Trevo525** [comment]
Merged. Thanks for your contribution!

**Pull request merged**
